import { Question } from "./types";

// ============================================
// FINANCE - RANKED QUESTIONS
// ============================================

export const financeRankedQuestions: Question[] = [
  {
    id: "fin-rank-1",
    type: "ranked",
    category: "finance",
    question: "Rank these companies by market cap (highest to lowest): Apple, Microsoft, Saudi Aramco, Alphabet",
    rankedList: ["Apple", "Microsoft", "Saudi Aramco", "Alphabet"],
  },
  {
    id: "fin-rank-2",
    type: "ranked",
    category: "finance",
    question: "Rank these countries by GDP (highest to lowest): USA, China, Germany, Japan",
    rankedList: ["USA", "China", "Japan", "Germany"],
  },
  {
    id: "fin-rank-3",
    type: "ranked",
    category: "finance",
    question: "Rank these banks by total assets (largest to smallest): JPMorgan Chase, Bank of America, ICBC, HSBC",
    rankedList: ["ICBC", "JPMorgan Chase", "Bank of America", "HSBC"],
  },
  {
    id: "fin-rank-4",
    type: "ranked",
    category: "finance",
    question: "Rank these tech companies by number of employees (most to fewest): Amazon, Walmart, Apple, Google",
    rankedList: ["Walmart", "Amazon", "Apple", "Google"],
  },
  {
    id: "fin-rank-5",
    type: "ranked",
    category: "finance",
    question: "Rank these stock exchanges by market cap (largest to smallest): NYSE, NASDAQ, Tokyo Stock Exchange, Shanghai Stock Exchange",
    rankedList: ["NYSE", "NASDAQ", "Shanghai Stock Exchange", "Tokyo Stock Exchange"],
  },
  {
    id: "fin-rank-6",
    type: "ranked",
    category: "finance",
    question: "Rank these companies by 2024 revenue (highest to lowest): Walmart, Amazon, Apple, ExxonMobil",
    rankedList: ["Walmart", "Amazon", "Apple", "ExxonMobil"],
  },
  {
    id: "fin-rank-7",
    type: "ranked",
    category: "finance",
    question: "Rank these currencies by trading volume (highest to lowest): US Dollar, Euro, Japanese Yen, British Pound",
    rankedList: ["US Dollar", "Euro", "Japanese Yen", "British Pound"],
  },
  {
    id: "fin-rank-8",
    type: "ranked",
    category: "finance",
    question: "Rank these countries by national debt (highest to lowest): USA, Japan, China, UK",
    rankedList: ["USA", "China", "Japan", "UK"],
  },
  {
    id: "fin-rank-9",
    type: "ranked",
    category: "finance",
    question: "Rank these billionaires by net worth (richest to poorest): Elon Musk, Jeff Bezos, Bernard Arnault, Mark Zuckerberg",
    rankedList: ["Elon Musk", "Jeff Bezos", "Bernard Arnault", "Mark Zuckerberg"],
  },
  {
    id: "fin-rank-10",
    type: "ranked",
    category: "finance",
    question: "Rank these companies by year founded (oldest to newest): IBM, Microsoft, Apple, Google",
    rankedList: ["IBM", "Apple", "Microsoft", "Google"],
  },
  {
    id: "fin-rank-11",
    type: "ranked",
    category: "finance",
    question: "Rank these credit card networks by purchase volume (highest to lowest): Visa, Mastercard, American Express, Discover",
    rankedList: ["Visa", "Mastercard", "American Express", "Discover"],
  },
  {
    id: "fin-rank-12",
    type: "ranked",
    category: "finance",
    question: "Rank these oil companies by revenue (highest to lowest): Saudi Aramco, Shell, ExxonMobil, Chevron",
    rankedList: ["Saudi Aramco", "Shell", "ExxonMobil", "Chevron"],
  },
  {
    id: "fin-rank-13",
    type: "ranked",
    category: "finance",
    question: "Rank these cryptocurrencies by market cap (highest to lowest): Bitcoin, Ethereum, Tether, BNB",
    rankedList: ["Bitcoin", "Ethereum", "Tether", "BNB"],
  },
  {
    id: "fin-rank-14",
    type: "ranked",
    category: "finance",
    question: "Rank these PE firms by assets under management (highest to lowest): Blackstone, KKR, Carlyle, Apollo",
    rankedList: ["Blackstone", "Apollo", "KKR", "Carlyle"],
  },
  {
    id: "fin-rank-15",
    type: "ranked",
    category: "finance",
    question: "Rank these retailers by number of US stores (most to fewest): Dollar General, Subway, Starbucks, McDonald's",
    rankedList: ["Dollar General", "Subway", "Starbucks", "McDonald's"],
  },
];

// ============================================
// SPORTS - RANKED QUESTIONS
// ============================================

export const sportsRankedQuestions: Question[] = [
  {
    id: "sport-rank-1",
    type: "ranked",
    category: "sports",
    question: "Rank these NFL teams by Super Bowl wins (most to fewest): Patriots, Steelers, Cowboys, 49ers",
    rankedList: ["Patriots", "Steelers", "49ers", "Cowboys"],
  },
  {
    id: "sport-rank-2",
    type: "ranked",
    category: "sports",
    question: "Rank these NBA teams by championships (most to fewest): Celtics, Lakers, Warriors, Bulls",
    rankedList: ["Celtics", "Lakers", "Warriors", "Bulls"],
  },
  {
    id: "sport-rank-3",
    type: "ranked",
    category: "sports",
    question: "Rank these MLB teams by World Series wins (most to fewest): Yankees, Cardinals, Red Sox, Giants",
    rankedList: ["Yankees", "Cardinals", "Red Sox", "Giants"],
  },
  {
    id: "sport-rank-4",
    type: "ranked",
    category: "sports",
    question: "Rank these countries by all-time Olympic gold medals (most to fewest): USA, Soviet Union, Great Britain, China",
    rankedList: ["USA", "Soviet Union", "Great Britain", "China"],
  },
  {
    id: "sport-rank-5",
    type: "ranked",
    category: "sports",
    question: "Rank these tennis players by Grand Slam titles (most to fewest): Djokovic, Federer, Nadal, Sampras",
    rankedList: ["Djokovic", "Nadal", "Federer", "Sampras"],
  },
  {
    id: "sport-rank-6",
    type: "ranked",
    category: "sports",
    question: "Rank these golfers by major championship wins (most to fewest): Jack Nicklaus, Tiger Woods, Walter Hagen, Gary Player",
    rankedList: ["Jack Nicklaus", "Tiger Woods", "Walter Hagen", "Gary Player"],
  },
  {
    id: "sport-rank-7",
    type: "ranked",
    category: "sports",
    question: "Rank these soccer clubs by UEFA Champions League titles (most to fewest): Real Madrid, AC Milan, Bayern Munich, Liverpool",
    rankedList: ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"],
  },
  {
    id: "sport-rank-8",
    type: "ranked",
    category: "sports",
    question: "Rank these countries by FIFA World Cup wins (most to fewest): Brazil, Germany, Italy, Argentina",
    rankedList: ["Brazil", "Germany", "Italy", "Argentina"],
  },
  {
    id: "sport-rank-9",
    type: "ranked",
    category: "sports",
    question: "Rank these NFL stadiums by seating capacity (largest to smallest): AT&T Stadium, MetLife Stadium, Lambeau Field, Arrowhead Stadium",
    rankedList: ["MetLife Stadium", "AT&T Stadium", "Lambeau Field", "Arrowhead Stadium"],
  },
  {
    id: "sport-rank-10",
    type: "ranked",
    category: "sports",
    question: "Rank these athletes by career earnings (highest to lowest): Michael Jordan, LeBron James, Tiger Woods, Cristiano Ronaldo",
    rankedList: ["Michael Jordan", "LeBron James", "Tiger Woods", "Cristiano Ronaldo"],
  },
  {
    id: "sport-rank-11",
    type: "ranked",
    category: "sports",
    question: "Rank these NHL teams by Stanley Cup wins (most to fewest): Canadiens, Maple Leafs, Red Wings, Bruins",
    rankedList: ["Canadiens", "Maple Leafs", "Red Wings", "Bruins"],
  },
  {
    id: "sport-rank-12",
    type: "ranked",
    category: "sports",
    question: "Rank these marathons by number of finishers (most to fewest): New York City, Berlin, Chicago, Boston",
    rankedList: ["New York City", "Chicago", "Berlin", "Boston"],
  },
  {
    id: "sport-rank-13",
    type: "ranked",
    category: "sports",
    question: "Rank these NBA players by career points (most to fewest): LeBron James, Kareem Abdul-Jabbar, Karl Malone, Kobe Bryant",
    rankedList: ["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"],
  },
  {
    id: "sport-rank-14",
    type: "ranked",
    category: "sports",
    question: "Rank these college football programs by national titles (most to fewest): Alabama, Notre Dame, Ohio State, USC",
    rankedList: ["Alabama", "Notre Dame", "Ohio State", "USC"],
  },
  {
    id: "sport-rank-15",
    type: "ranked",
    category: "sports",
    question: "Rank these sports by average MLB player salary (highest to lowest): Baseball, Basketball, Football, Hockey",
    rankedList: ["Basketball", "Baseball", "Hockey", "Football"],
  },
];

// ============================================
// GENERAL KNOWLEDGE - RANKED QUESTIONS
// ============================================

export const generalRankedQuestions: Question[] = [
  {
    id: "gen-rank-1",
    type: "ranked",
    category: "general",
    question: "Rank these countries by land area (largest to smallest): Russia, Canada, USA, China",
    rankedList: ["Russia", "Canada", "USA", "China"],
  },
  {
    id: "gen-rank-2",
    type: "ranked",
    category: "general",
    question: "Rank these languages by number of native speakers (most to fewest): Mandarin, Spanish, English, Hindi",
    rankedList: ["Mandarin", "Spanish", "English", "Hindi"],
  },
  {
    id: "gen-rank-3",
    type: "ranked",
    category: "general",
    question: "Rank these rivers by length (longest to shortest): Nile, Amazon, Yangtze, Mississippi",
    rankedList: ["Nile", "Amazon", "Yangtze", "Mississippi"],
  },
  {
    id: "gen-rank-4",
    type: "ranked",
    category: "general",
    question: "Rank these buildings by height (tallest to shortest): Burj Khalifa, Shanghai Tower, Empire State Building, Willis Tower",
    rankedList: ["Burj Khalifa", "Shanghai Tower", "Willis Tower", "Empire State Building"],
  },
  {
    id: "gen-rank-5",
    type: "ranked",
    category: "general",
    question: "Rank these countries by annual tourist arrivals (most to fewest): France, Spain, USA, China",
    rankedList: ["France", "Spain", "USA", "China"],
  },
  {
    id: "gen-rank-6",
    type: "ranked",
    category: "general",
    question: "Rank these cities by population (largest to smallest): Tokyo, Delhi, Shanghai, São Paulo",
    rankedList: ["Tokyo", "Delhi", "Shanghai", "São Paulo"],
  },
  {
    id: "gen-rank-7",
    type: "ranked",
    category: "general",
    question: "Rank these universities by year founded (oldest to newest): Oxford, Harvard, Cambridge, Yale",
    rankedList: ["Oxford", "Cambridge", "Harvard", "Yale"],
  },
  {
    id: "gen-rank-8",
    type: "ranked",
    category: "general",
    question: "Rank these airports by passenger traffic (busiest to least busy): Atlanta, Dubai, Dallas, Tokyo Haneda",
    rankedList: ["Atlanta", "Dubai", "Dallas", "Tokyo Haneda"],
  },
  {
    id: "gen-rank-9",
    type: "ranked",
    category: "general",
    question: "Rank these planets by distance from the Sun (closest to farthest): Mercury, Venus, Mars, Jupiter",
    rankedList: ["Mercury", "Venus", "Mars", "Jupiter"],
  },
  {
    id: "gen-rank-10",
    type: "ranked",
    category: "general",
    question: "Rank these oceans by size (largest to smallest): Pacific, Atlantic, Indian, Southern",
    rankedList: ["Pacific", "Atlantic", "Indian", "Southern"],
  },
  {
    id: "gen-rank-11",
    type: "ranked",
    category: "general",
    question: "Rank these social media platforms by monthly active users (most to fewest): Facebook, YouTube, WhatsApp, Instagram",
    rankedList: ["Facebook", "YouTube", "WhatsApp", "Instagram"],
  },
  {
    id: "gen-rank-12",
    type: "ranked",
    category: "general",
    question: "Rank these movies by worldwide box office (highest to lowest): Avatar, Avengers: Endgame, Titanic, Star Wars: The Force Awakens",
    rankedList: ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
  },
  {
    id: "gen-rank-13",
    type: "ranked",
    category: "general",
    question: "Rank these countries by coffee consumption per capita (highest to lowest): Finland, Norway, USA, Italy",
    rankedList: ["Finland", "Norway", "Italy", "USA"],
  },
  {
    id: "gen-rank-14",
    type: "ranked",
    category: "general",
    question: "Rank these deserts by size (largest to smallest): Sahara, Arabian, Gobi, Kalahari",
    rankedList: ["Sahara", "Arabian", "Gobi", "Kalahari"],
  },
  {
    id: "gen-rank-15",
    type: "ranked",
    category: "general",
    question: "Rank these empires by peak land area (largest to smallest): British Empire, Mongol Empire, Russian Empire, Spanish Empire",
    rankedList: ["British Empire", "Mongol Empire", "Russian Empire", "Spanish Empire"],
  },
];

// ============================================
// FINANCE - OPEN-ENDED QUESTIONS
// ============================================

export const financeOpenQuestions: Question[] = [
  {
    id: "fin-open-1",
    type: "open",
    category: "finance",
    question: "Name a company in the S&P 500 that starts with the letter 'A'",
    answers: {
      "Apple": 10,
      "Amazon": 15,
      "Alphabet": 20,
      "Adobe": 40,
      "AMD": 45,
      "American Express": 50,
      "Accenture": 60,
      "Abbott": 65,
      "AbbVie": 70,
      "Aon": 80,
      "Analog Devices": 85,
      "Amphenol": 90,
      "Aflac": 92,
      "Autodesk": 94,
      "ADP": 88,
    },
  },
  {
    id: "fin-open-2",
    type: "open",
    category: "finance",
    question: "Name a major stock exchange",
    answers: {
      "NYSE": 10,
      "New York Stock Exchange": 10,
      "NASDAQ": 15,
      "London Stock Exchange": 30,
      "Tokyo Stock Exchange": 40,
      "Shanghai Stock Exchange": 50,
      "Hong Kong Stock Exchange": 55,
      "Euronext": 65,
      "Shenzhen Stock Exchange": 70,
      "Toronto Stock Exchange": 75,
      "Deutsche Börse": 80,
      "Bombay Stock Exchange": 85,
      "Australian Securities Exchange": 90,
      "Korea Exchange": 92,
      "Swiss Exchange": 95,
    },
  },
  {
    id: "fin-open-3",
    type: "open",
    category: "finance",
    question: "Name a Fortune 500 company headquartered in Texas",
    answers: {
      "ExxonMobil": 15,
      "AT&T": 20,
      "Dell": 35,
      "American Airlines": 40,
      "Phillips 66": 50,
      "Valero": 55,
      "ConocoPhillips": 60,
      "Sysco": 65,
      "Oracle": 45,
      "HP": 50,
      "Hewlett Packard": 50,
      "Kimberly-Clark": 70,
      "Texas Instruments": 55,
      "Fluor": 80,
      "USAA": 75,
    },
  },
  {
    id: "fin-open-4",
    type: "open",
    category: "finance",
    question: "Name a cryptocurrency",
    answers: {
      "Bitcoin": 5,
      "Ethereum": 15,
      "Dogecoin": 25,
      "Litecoin": 40,
      "Ripple": 45,
      "XRP": 45,
      "Cardano": 50,
      "Solana": 35,
      "Polkadot": 60,
      "Chainlink": 65,
      "Tether": 55,
      "USDC": 58,
      "Avalanche": 70,
      "Polygon": 72,
      "Shiba Inu": 45,
      "BNB": 50,
      "Tron": 75,
      "Stellar": 78,
    },
  },
  {
    id: "fin-open-5",
    type: "open",
    category: "finance",
    question: "Name a company Warren Buffett's Berkshire Hathaway has invested in",
    answers: {
      "Apple": 10,
      "Coca-Cola": 20,
      "Bank of America": 30,
      "American Express": 35,
      "Chevron": 45,
      "Occidental Petroleum": 50,
      "Kraft Heinz": 55,
      "Moody's": 60,
      "HP": 65,
      "Paramount": 70,
      "Kroger": 75,
      "Visa": 80,
      "Mastercard": 82,
      "Amazon": 85,
      "Snowflake": 88,
      "Geico": 40,
    },
  },
  {
    id: "fin-open-6",
    type: "open",
    category: "finance",
    question: "Name a major US bank",
    answers: {
      "Chase": 10,
      "JPMorgan": 10,
      "JPMorgan Chase": 10,
      "Bank of America": 15,
      "Wells Fargo": 20,
      "Citibank": 25,
      "Citi": 25,
      "US Bank": 35,
      "PNC": 45,
      "Truist": 50,
      "Capital One": 40,
      "TD Bank": 55,
      "Goldman Sachs": 30,
      "Morgan Stanley": 32,
      "Charles Schwab": 60,
      "Fifth Third": 70,
      "Regions": 75,
    },
  },
  {
    id: "fin-open-7",
    type: "open",
    category: "finance",
    question: "Name a company that has done an IPO since 2020",
    answers: {
      "Airbnb": 15,
      "DoorDash": 20,
      "Coinbase": 25,
      "Rivian": 30,
      "Robinhood": 35,
      "Roblox": 40,
      "Instacart": 45,
      "Arm": 50,
      "Reddit": 35,
      "Snowflake": 55,
      "Unity": 60,
      "Bumble": 65,
      "Affirm": 70,
      "Klaviyo": 80,
      "Birkenstock": 85,
    },
  },
  {
    id: "fin-open-8",
    type: "open",
    category: "finance",
    question: "Name a major credit card company",
    answers: {
      "Visa": 10,
      "Mastercard": 15,
      "American Express": 20,
      "Amex": 20,
      "Discover": 30,
      "Capital One": 35,
      "Chase": 40,
      "Citi": 50,
      "Barclays": 60,
      "Synchrony": 70,
    },
  },
  {
    id: "fin-open-9",
    type: "open",
    category: "finance",
    question: "Name a Big Four accounting firm",
    answers: {
      "Deloitte": 25,
      "PwC": 25,
      "PricewaterhouseCoopers": 25,
      "EY": 25,
      "Ernst & Young": 25,
      "KPMG": 25,
    },
  },
  {
    id: "fin-open-10",
    type: "open",
    category: "finance",
    question: "Name a company in the 'Magnificent Seven' tech stocks",
    answers: {
      "Apple": 15,
      "Microsoft": 15,
      "Google": 15,
      "Alphabet": 15,
      "Amazon": 15,
      "Meta": 20,
      "Facebook": 20,
      "Nvidia": 15,
      "Tesla": 20,
    },
  },
  {
    id: "fin-open-11",
    type: "open",
    category: "finance",
    question: "Name a major private equity firm",
    answers: {
      "Blackstone": 20,
      "KKR": 25,
      "Carlyle": 30,
      "Apollo": 35,
      "TPG": 45,
      "Bain Capital": 40,
      "Warburg Pincus": 55,
      "Advent": 60,
      "CVC": 65,
      "EQT": 70,
      "Thoma Bravo": 50,
      "Vista Equity": 55,
      "Silver Lake": 58,
    },
  },
  {
    id: "fin-open-12",
    type: "open",
    category: "finance",
    question: "Name a company that pays dividends in the Dow Jones Industrial Average",
    answers: {
      "Coca-Cola": 15,
      "Johnson & Johnson": 20,
      "Procter & Gamble": 25,
      "McDonald's": 30,
      "Verizon": 35,
      "Chevron": 40,
      "IBM": 45,
      "3M": 50,
      "Caterpillar": 55,
      "Walmart": 35,
      "Home Depot": 40,
      "JPMorgan": 45,
      "Goldman Sachs": 50,
      "Travelers": 65,
      "Amgen": 60,
    },
  },
];

// ============================================
// SPORTS - OPEN-ENDED QUESTIONS
// ============================================

export const sportsOpenQuestions: Question[] = [
  {
    id: "sport-open-1",
    type: "open",
    category: "sports",
    question: "Name an NFL team that has never won a Super Bowl",
    answers: {
      "Buffalo Bills": 20,
      "Bills": 20,
      "Minnesota Vikings": 25,
      "Vikings": 25,
      "Cincinnati Bengals": 30,
      "Bengals": 30,
      "Atlanta Falcons": 35,
      "Falcons": 35,
      "Carolina Panthers": 40,
      "Panthers": 40,
      "Cleveland Browns": 45,
      "Browns": 45,
      "Detroit Lions": 50,
      "Lions": 50,
      "Jacksonville Jaguars": 60,
      "Jaguars": 60,
      "Tennessee Titans": 65,
      "Titans": 65,
      "Houston Texans": 70,
      "Texans": 70,
      "Arizona Cardinals": 75,
      "Cardinals": 75,
      "Los Angeles Chargers": 80,
      "Chargers": 80,
    },
  },
  {
    id: "sport-open-2",
    type: "open",
    category: "sports",
    question: "Name a country that has won the FIFA World Cup",
    answers: {
      "Brazil": 15,
      "Germany": 20,
      "Italy": 25,
      "Argentina": 30,
      "France": 35,
      "Uruguay": 50,
      "England": 55,
      "Spain": 60,
    },
  },
  {
    id: "sport-open-3",
    type: "open",
    category: "sports",
    question: "Name an MLB team that has won the World Series",
    answers: {
      "Yankees": 10,
      "New York Yankees": 10,
      "Cardinals": 20,
      "St. Louis Cardinals": 20,
      "Red Sox": 25,
      "Boston Red Sox": 25,
      "Dodgers": 30,
      "Los Angeles Dodgers": 30,
      "Giants": 35,
      "San Francisco Giants": 35,
      "Athletics": 40,
      "Oakland Athletics": 40,
      "Cubs": 45,
      "Chicago Cubs": 45,
      "Braves": 50,
      "Atlanta Braves": 50,
      "Astros": 55,
      "Houston Astros": 55,
      "Twins": 60,
      "Tigers": 65,
      "Reds": 70,
      "Pirates": 75,
      "White Sox": 70,
      "Phillies": 72,
      "Royals": 78,
      "Nationals": 80,
      "Marlins": 85,
      "Diamondbacks": 88,
      "Rangers": 82,
    },
  },
  {
    id: "sport-open-4",
    type: "open",
    category: "sports",
    question: "Name a Heisman Trophy winner",
    answers: {
      "Lamar Jackson": 30,
      "Kyler Murray": 35,
      "Joe Burrow": 25,
      "DeVonta Smith": 40,
      "Bryce Young": 35,
      "Caleb Williams": 30,
      "Tim Tebow": 25,
      "Cam Newton": 30,
      "Johnny Manziel": 35,
      "Marcus Mariota": 45,
      "Derrick Henry": 40,
      "Baker Mayfield": 38,
      "Robert Griffin III": 50,
      "RG3": 50,
      "Jameis Winston": 55,
      "Carson Palmer": 60,
      "Matt Leinart": 65,
      "Reggie Bush": 35,
      "Troy Smith": 70,
      "Sam Bradford": 58,
    },
  },
  {
    id: "sport-open-5",
    type: "open",
    category: "sports",
    question: "Name an NBA player who has won MVP",
    answers: {
      "LeBron James": 10,
      "LeBron": 10,
      "Michael Jordan": 15,
      "Stephen Curry": 20,
      "Steph Curry": 20,
      "Kevin Durant": 25,
      "Giannis Antetokounmpo": 30,
      "Giannis": 30,
      "Nikola Jokic": 25,
      "Jokic": 25,
      "Kobe Bryant": 35,
      "Kobe": 35,
      "Tim Duncan": 40,
      "Shaquille O'Neal": 45,
      "Shaq": 45,
      "Dirk Nowitzki": 50,
      "Steve Nash": 55,
      "Russell Westbrook": 48,
      "James Harden": 52,
      "Derrick Rose": 60,
      "Joel Embiid": 35,
    },
  },
  {
    id: "sport-open-6",
    type: "open",
    category: "sports",
    question: "Name a golfer who has won a major championship",
    answers: {
      "Tiger Woods": 10,
      "Jack Nicklaus": 25,
      "Phil Mickelson": 30,
      "Rory McIlroy": 35,
      "Jordan Spieth": 45,
      "Brooks Koepka": 50,
      "Dustin Johnson": 55,
      "Jon Rahm": 45,
      "Scottie Scheffler": 40,
      "Justin Thomas": 60,
      "Collin Morikawa": 65,
      "Bryson DeChambeau": 58,
      "Xander Schauffele": 55,
      "Arnold Palmer": 40,
      "Gary Player": 50,
      "Tom Watson": 55,
      "Sergio Garcia": 70,
    },
  },
  {
    id: "sport-open-7",
    type: "open",
    category: "sports",
    question: "Name an NFL quarterback who has won a Super Bowl",
    answers: {
      "Tom Brady": 10,
      "Patrick Mahomes": 15,
      "Peyton Manning": 25,
      "Eli Manning": 35,
      "Aaron Rodgers": 40,
      "Drew Brees": 45,
      "Russell Wilson": 50,
      "Ben Roethlisberger": 55,
      "Joe Montana": 30,
      "John Elway": 45,
      "Troy Aikman": 50,
      "Brett Favre": 55,
      "Terry Bradshaw": 60,
      "Joe Namath": 65,
      "Nick Foles": 70,
      "Matthew Stafford": 55,
    },
  },
  {
    id: "sport-open-8",
    type: "open",
    category: "sports",
    question: "Name a Premier League club",
    answers: {
      "Manchester United": 10,
      "Man United": 10,
      "Liverpool": 15,
      "Chelsea": 20,
      "Arsenal": 25,
      "Manchester City": 15,
      "Man City": 15,
      "Tottenham": 35,
      "Spurs": 35,
      "Newcastle": 50,
      "West Ham": 55,
      "Everton": 60,
      "Aston Villa": 55,
      "Brighton": 65,
      "Wolves": 70,
      "Crystal Palace": 72,
      "Fulham": 75,
      "Bournemouth": 78,
      "Brentford": 80,
      "Nottingham Forest": 75,
    },
  },
  {
    id: "sport-open-9",
    type: "open",
    category: "sports",
    question: "Name a city that has hosted the Summer Olympics",
    answers: {
      "Los Angeles": 15,
      "London": 20,
      "Paris": 15,
      "Tokyo": 25,
      "Beijing": 30,
      "Sydney": 35,
      "Atlanta": 40,
      "Barcelona": 45,
      "Athens": 50,
      "Rio de Janeiro": 45,
      "Rio": 45,
      "Seoul": 55,
      "Munich": 60,
      "Montreal": 65,
      "Moscow": 70,
      "Berlin": 75,
      "Rome": 70,
      "Mexico City": 72,
      "Amsterdam": 85,
      "Stockholm": 88,
      "St. Louis": 92,
    },
  },
  {
    id: "sport-open-10",
    type: "open",
    category: "sports",
    question: "Name a Formula 1 World Champion",
    answers: {
      "Lewis Hamilton": 10,
      "Max Verstappen": 15,
      "Michael Schumacher": 20,
      "Sebastian Vettel": 30,
      "Ayrton Senna": 40,
      "Fernando Alonso": 45,
      "Niki Lauda": 55,
      "Alain Prost": 60,
      "Kimi Räikkönen": 50,
      "Mika Häkkinen": 65,
      "Jenson Button": 70,
      "Nico Rosberg": 58,
      "Jacques Villeneuve": 75,
      "Damon Hill": 78,
    },
  },
  {
    id: "sport-open-11",
    type: "open",
    category: "sports",
    question: "Name an active NFL running back",
    answers: {
      "Derrick Henry": 15,
      "Saquon Barkley": 20,
      "Josh Jacobs": 35,
      "Nick Chubb": 40,
      "Jonathan Taylor": 35,
      "Austin Ekeler": 45,
      "Alvin Kamara": 40,
      "Joe Mixon": 50,
      "Tony Pollard": 55,
      "Travis Etienne": 50,
      "Breece Hall": 45,
      "Bijan Robinson": 40,
      "Jahmyr Gibbs": 55,
      "Isiah Pacheco": 60,
      "Rachaad White": 65,
      "Kenneth Walker": 58,
    },
  },
  {
    id: "sport-open-12",
    type: "open",
    category: "sports",
    question: "Name a Tennis Grand Slam tournament",
    answers: {
      "Wimbledon": 20,
      "US Open": 20,
      "Australian Open": 30,
      "French Open": 30,
      "Roland Garros": 40,
    },
  },
];

// ============================================
// GENERAL KNOWLEDGE - OPEN-ENDED QUESTIONS
// ============================================

export const generalOpenQuestions: Question[] = [
  {
    id: "gen-open-1",
    type: "open",
    category: "general",
    question: "Name a country that has hosted the Summer Olympics",
    answers: {
      "USA": 10,
      "United States": 10,
      "China": 20,
      "UK": 25,
      "United Kingdom": 25,
      "Great Britain": 25,
      "France": 20,
      "Japan": 30,
      "Australia": 35,
      "Germany": 40,
      "Greece": 45,
      "Brazil": 50,
      "South Korea": 55,
      "Spain": 60,
      "Italy": 62,
      "Mexico": 65,
      "Canada": 70,
      "Russia": 72,
      "Sweden": 80,
      "Netherlands": 85,
      "Belgium": 88,
      "Finland": 90,
    },
  },
  {
    id: "gen-open-2",
    type: "open",
    category: "general",
    question: "Name a country in the European Union",
    answers: {
      "Germany": 10,
      "France": 15,
      "Italy": 20,
      "Spain": 25,
      "Netherlands": 35,
      "Poland": 40,
      "Belgium": 45,
      "Sweden": 50,
      "Austria": 55,
      "Denmark": 58,
      "Finland": 60,
      "Ireland": 48,
      "Portugal": 52,
      "Greece": 55,
      "Czech Republic": 65,
      "Czechia": 65,
      "Romania": 70,
      "Hungary": 68,
      "Croatia": 75,
      "Slovakia": 78,
      "Bulgaria": 80,
      "Luxembourg": 82,
      "Slovenia": 85,
      "Latvia": 88,
      "Lithuania": 87,
      "Estonia": 89,
      "Cyprus": 90,
      "Malta": 92,
    },
  },
  {
    id: "gen-open-3",
    type: "open",
    category: "general",
    question: "Name a landlocked country",
    answers: {
      "Switzerland": 15,
      "Austria": 25,
      "Bolivia": 35,
      "Mongolia": 45,
      "Nepal": 40,
      "Paraguay": 55,
      "Hungary": 50,
      "Czech Republic": 48,
      "Czechia": 48,
      "Slovakia": 60,
      "Ethiopia": 55,
      "Afghanistan": 45,
      "Kazakhstan": 50,
      "Uzbekistan": 65,
      "Laos": 70,
      "Belarus": 58,
      "Serbia": 62,
      "Rwanda": 75,
      "Uganda": 72,
      "Zimbabwe": 68,
      "Zambia": 70,
      "Mali": 78,
      "Niger": 80,
      "Chad": 82,
      "Botswana": 75,
      "Luxembourg": 55,
      "Liechtenstein": 85,
      "Andorra": 88,
      "San Marino": 90,
      "Vatican City": 92,
    },
  },
  {
    id: "gen-open-4",
    type: "open",
    category: "general",
    question: "Name a Shakespeare play",
    answers: {
      "Hamlet": 15,
      "Romeo and Juliet": 10,
      "Macbeth": 20,
      "Othello": 30,
      "King Lear": 35,
      "A Midsummer Night's Dream": 40,
      "The Tempest": 50,
      "Julius Caesar": 45,
      "Much Ado About Nothing": 55,
      "Twelfth Night": 58,
      "The Merchant of Venice": 52,
      "As You Like It": 65,
      "The Taming of the Shrew": 60,
      "Richard III": 62,
      "Henry V": 68,
      "Antony and Cleopatra": 70,
      "The Winter's Tale": 75,
      "Coriolanus": 85,
      "Titus Andronicus": 88,
      "Measure for Measure": 82,
    },
  },
  {
    id: "gen-open-5",
    type: "open",
    category: "general",
    question: "Name a chemical element",
    answers: {
      "Oxygen": 10,
      "Hydrogen": 15,
      "Carbon": 18,
      "Gold": 20,
      "Silver": 25,
      "Iron": 22,
      "Nitrogen": 30,
      "Helium": 28,
      "Copper": 35,
      "Platinum": 45,
      "Uranium": 50,
      "Mercury": 48,
      "Lead": 40,
      "Zinc": 52,
      "Aluminum": 38,
      "Titanium": 55,
      "Nickel": 58,
      "Sodium": 42,
      "Potassium": 55,
      "Calcium": 48,
      "Chlorine": 60,
      "Neon": 62,
      "Argon": 70,
      "Lithium": 65,
      "Cobalt": 72,
      "Tin": 68,
      "Tungsten": 78,
      "Plutonium": 75,
    },
  },
  {
    id: "gen-open-6",
    type: "open",
    category: "general",
    question: "Name a Nobel Prize category",
    answers: {
      "Peace": 15,
      "Physics": 20,
      "Chemistry": 25,
      "Medicine": 30,
      "Literature": 35,
      "Economics": 40,
      "Physiology": 45,
      "Physiology or Medicine": 45,
    },
  },
  {
    id: "gen-open-7",
    type: "open",
    category: "general",
    question: "Name a US state capital",
    answers: {
      "Austin": 15,
      "Sacramento": 25,
      "Albany": 40,
      "Tallahassee": 50,
      "Atlanta": 30,
      "Denver": 28,
      "Boston": 20,
      "Phoenix": 32,
      "Columbus": 45,
      "Harrisburg": 55,
      "Springfield": 48,
      "Nashville": 35,
      "Raleigh": 52,
      "Lansing": 60,
      "Olympia": 65,
      "Salem": 58,
      "Madison": 55,
      "Baton Rouge": 62,
      "Frankfort": 75,
      "Juneau": 70,
      "Honolulu": 45,
      "Santa Fe": 68,
      "Annapolis": 72,
      "Trenton": 78,
      "Dover": 80,
      "Pierre": 85,
      "Bismarck": 82,
      "Montpelier": 88,
      "Carson City": 90,
      "Jefferson City": 75,
    },
  },
  {
    id: "gen-open-8",
    type: "open",
    category: "general",
    question: "Name a world wonder (ancient or modern)",
    answers: {
      "Great Wall of China": 15,
      "Great Wall": 15,
      "Pyramids of Giza": 20,
      "Pyramids": 20,
      "Machu Picchu": 30,
      "Colosseum": 35,
      "Taj Mahal": 25,
      "Christ the Redeemer": 45,
      "Petra": 50,
      "Chichen Itza": 55,
      "Statue of Zeus": 70,
      "Hanging Gardens of Babylon": 65,
      "Hanging Gardens": 65,
      "Lighthouse of Alexandria": 75,
      "Temple of Artemis": 80,
      "Mausoleum at Halicarnassus": 85,
      "Colossus of Rhodes": 78,
    },
  },
  {
    id: "gen-open-9",
    type: "open",
    category: "general",
    question: "Name a streaming service",
    answers: {
      "Netflix": 10,
      "Disney+": 20,
      "Disney Plus": 20,
      "Hulu": 25,
      "Amazon Prime": 22,
      "Prime Video": 22,
      "HBO Max": 30,
      "Max": 30,
      "Apple TV+": 40,
      "Apple TV Plus": 40,
      "Peacock": 50,
      "Paramount+": 55,
      "Paramount Plus": 55,
      "YouTube TV": 60,
      "Spotify": 45,
      "Tubi": 70,
      "Crunchyroll": 75,
      "ESPN+": 65,
    },
  },
  {
    id: "gen-open-10",
    type: "open",
    category: "general",
    question: "Name an Ivy League university",
    answers: {
      "Harvard": 15,
      "Yale": 20,
      "Princeton": 25,
      "Columbia": 30,
      "Penn": 35,
      "Pennsylvania": 35,
      "University of Pennsylvania": 35,
      "Brown": 45,
      "Dartmouth": 50,
      "Cornell": 40,
    },
  },
  {
    id: "gen-open-11",
    type: "open",
    category: "general",
    question: "Name a programming language",
    answers: {
      "Python": 10,
      "JavaScript": 15,
      "Java": 18,
      "C++": 25,
      "C": 30,
      "C#": 35,
      "Ruby": 50,
      "Go": 55,
      "Rust": 60,
      "Swift": 52,
      "Kotlin": 65,
      "PHP": 45,
      "TypeScript": 40,
      "SQL": 38,
      "R": 58,
      "MATLAB": 68,
      "Perl": 72,
      "Scala": 75,
      "Haskell": 80,
      "Lua": 78,
      "Assembly": 82,
      "COBOL": 85,
      "Fortran": 88,
    },
  },
  {
    id: "gen-open-12",
    type: "open",
    category: "general",
    question: "Name a fast food chain",
    answers: {
      "McDonald's": 10,
      "Burger King": 20,
      "Wendy's": 25,
      "Taco Bell": 28,
      "Subway": 22,
      "Chick-fil-A": 18,
      "KFC": 30,
      "Popeyes": 40,
      "Chipotle": 35,
      "Five Guys": 45,
      "In-N-Out": 48,
      "Arby's": 55,
      "Sonic": 58,
      "Jack in the Box": 62,
      "Panda Express": 50,
      "Dunkin'": 42,
      "Starbucks": 32,
      "Domino's": 38,
      "Pizza Hut": 40,
      "Papa John's": 52,
      "Little Caesars": 60,
      "Wingstop": 65,
      "Shake Shack": 55,
      "Raising Cane's": 58,
      "Whataburger": 62,
      "Culver's": 70,
    },
  },
];

// ============================================
// EXPORT ALL QUESTIONS
// ============================================

export const allQuestions: Question[] = [
  ...financeRankedQuestions,
  ...sportsRankedQuestions,
  ...generalRankedQuestions,
  ...financeOpenQuestions,
  ...sportsOpenQuestions,
  ...generalOpenQuestions,
];

// Helper to get questions by category
export function getQuestionsByCategory(category: "finance" | "sports" | "general"): Question[] {
  return allQuestions.filter((q) => q.category === category);
}

// Helper to get questions by type
export function getQuestionsByType(type: "open" | "ranked"): Question[] {
  return allQuestions.filter((q) => q.type === type);
}
